[project]
name = "dc26-vatican-explorer"
version = "v0"
description = "Vatican Explorer is a web app that enables researchers and journalists to easily explore what popes have talked about and compare differences across popes."
readme = "README.md"
authors = [
  {name = "Ritika Giri", email = "ritika.giri3@gmail.com"}
]
maintainers = [
  {name = "Ritika Giri", email = "ritika.giri3@gmail.com"}
]
classifiers = [
    # TODO
]
license = {text = "MIT"}
dependencies = [
  "typer"
]
requires-python = ">= 3.10"

[project.optional-dependencies]
test = [
    "coverage",  # testing
    "pytest",  # testing
    "ruff",  # linting
    "ty", # checking types
    "ipdb", # debugging
]

[project.urls]
bugs = "https://github.com/ritika-giri/dc26_vatican_explorer/issues"
changelog = "https://github.com/ritika-giri/dc26_vatican_explorer/blob/master/changelog.md"
homepage = "https://github.com/ritika-giri/dc26_vatican_explorer"

[project.scripts]
dc26_vatican_explorer = "dc26_vatican_explorer.cli:app"

[tool.ty]
# All rules are enabled as "error" by default; no need to specify unless overriding.
# Example override: relax a rule for the entire project (uncomment if needed).
# rules.TY015 = "warn"  # For invalid-argument-type, warn instead of error.

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.uv]
package = true
